# Generated by Django 2.1 on 2018-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfix', models.CharField(max_length=1000000)),
                ('theme', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
                ('key_classify', models.ForeignKey(on_delete=None, to='app01.Blog')),
            ],
            options={
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Fanstoeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '互粉',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Suberror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('do_time', models.CharField(max_length=100)),
                ('do_what', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '保障单',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('img', models.ImageField(upload_to='logo')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=100)),
                ('ctime', models.TimeField()),
                ('key_classify', models.ForeignKey(on_delete=None, to='app01.Classify')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='WordToLable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelid', models.ForeignKey(on_delete=None, to='app01.Label')),
                ('wordid', models.ForeignKey(on_delete=None, to='app01.Word')),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='suberror',
            name='processor',
            field=models.ForeignKey(on_delete=None, related_name='douser', to='app01.User'),
        ),
        migrations.AddField(
            model_name='suberror',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='subuser', to='app01.User'),
        ),
        migrations.AddField(
            model_name='fanstoeach',
            name='idol',
            field=models.ForeignKey(on_delete=None, related_name='idone', to='app01.User'),
        ),
        migrations.AddField(
            model_name='fanstoeach',
            name='pm',
            field=models.ForeignKey(on_delete=None, related_name='idanthor', to='app01.User'),
        ),
        migrations.AddField(
            model_name='blog',
            name='key_label',
            field=models.ForeignKey(on_delete=None, to='app01.Label'),
        ),
        migrations.AddField(
            model_name='blog',
            name='key_user',
            field=models.ForeignKey(on_delete=None, to='app01.User', unique=True),
        ),
    ]
